# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f2e8cfdd203b5bc3123306e58a7afc94de1759cb7678979e9b5c2d624c927870afefad9d4c41af68546fa539c476fbb2a4f319d4f36cc180b79c042c341be2f4

test:
  secret_key_base: 288f8eedfc28c01ef0ad08d70a015b6809e3ff8897b6e0425696bb226cc65db73b7d4e920d29de186783b18c2ba84fe5e59fb662eeb6f73c4f78acfd07631972

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
